#!/usr/bin/env python3
"""Build tables (LaTeX and Markdown) and charts for slides from results/*.csv.

Output files (results/):
  sizes.csv          -> pgfplots chart in slides (columns lang,text,data,rodata,debug)
  table_sizes.tex    -> \\input into the “Object file size” slide
  table_symbols.tex  -> \\input into the “Symbols, sections, and relocations” slide
  table_time.tex     -> \\input into the “Time, memory, and linker work” slide
  summary.md         -> the same numbers in Markdown (for README and debugging)
  chart_*.png        -> images, if matplotlib is installed
Values are summed across all programs in the corpus.
"""
import argparse
import csv
from collections import defaultdict
from pathlib import Path

import toolchain as tc

NUM = ("obj_bytes", "sec_count", "sec_text", "sec_data", "sec_rodata", "sec_debug", "sec_eh",
       "sec_other", "n_groups", "n_text_sections", "rel_total", "rel_code", "rel_debug",
       "sym_def", "sym_undef", "sym_weak", "sym_global", "sym_local", "compile_ms_median",
       "compile_cpu_ms", "max_rss_kb")


def load(results):
    with open(results / "metrics.csv") as f:
        rows = list(csv.DictReader(f))
    agg = defaultdict(lambda: defaultdict(float))
    progs = defaultdict(set)
    for r in rows:
        key = (r["lang"], r["mode"])
        progs[key].add(r["prog"])
        for k in NUM:
            v = float(r[k])
            if k == "max_rss_kb":
                agg[key][k] = max(agg[key][k], v)      # пик памяти: максимум по программам
            else:
                agg[key][k] += v
    types = defaultdict(lambda: defaultdict(int))
    with open(results / "relocs.csv") as f:
        for r in csv.DictReader(f):
            types[(r["lang"], r["mode"])][r["type"]] += int(r["count"])
    return agg, types, progs


def n(x):
    return f"{int(round(x)):,}".replace(",", r"\,")


def tex_table(path, header, body, colspec):
    with open(path, "w") as f:
        f.write("% generated by scripts/report.py, do not edit manually\n")
        f.write(f"\\begin{{tabular}}{{{colspec}}}\n\\toprule\n{header} \\\\\n\\midrule\n")
        for row in body:
            f.write(" & ".join(row) + " \\\\\n")
        f.write("\\bottomrule\n\\end{tabular}\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--results", default=str(tc.ROOT / "results"))
    ap.add_argument("--modes", default="O2,O2g", help="modes for tables")
    ap.add_argument("--chart-mode", default="O2g", help="mode for sizes.csv and charts")
    a = ap.parse_args()
    res = Path(a.results)
    agg, rtypes, progs = load(res)
    modes = a.modes.split(",")
    langs = [l for l in tc.LANGS if any(k[0] == l for k in agg)]
    keys = [(l, m) for l in langs for m in modes if (l, m) in agg]
    md = ["# Summary (sum across the corpus)\n"]

    # --- таблица размеров
    body, mdrows = [], []
    for l, m in keys:
        d = agg[(l, m)]
        label = f"{tc.LANG_NAME[l]} {m}"
        body.append([label, n(d["obj_bytes"]), n(d["sec_text"]), n(d["sec_data"] + d["sec_rodata"]),
                     n(d["sec_debug"]), n(d["sec_eh"])])
        mdrows.append(f"| {label} | {int(d['obj_bytes'])} | {int(d['sec_text'])} | "
                      f"{int(d['sec_data'] + d['sec_rodata'])} | {int(d['sec_debug'])} | {int(d['sec_eh'])} |")
    tex_table(res / "table_sizes.tex",
              r"Language / mode & total & \texttt{.text} & \texttt{.data+.rodata} & "
              r"\texttt{.debug\_*} & \texttt{.eh\_frame}", body, "@{}lrrrrr@{}")
    md += ["## Sizes, bytes\n", "| Language / mode | total | .text | .data+.rodata | .debug_* | .eh_frame |",
           "|---|---:|---:|---:|---:|---:|", *mdrows, ""]

    # --- таблица символов
    body, mdrows = [], []
    for l, m in keys:
        d = agg[(l, m)]
        top = max(rtypes[(l, m)].items(), key=lambda kv: kv[1])[0] if rtypes[(l, m)] else "-"
        label = f"{tc.LANG_NAME[l]} {m}"
        body.append([label, n(d["sec_count"]), f"{n(d['sym_def'])}/{n(d['sym_undef'])}",
                     n(d["sym_weak"]), n(d["rel_total"]), r"\texttt{" + top.replace("_", r"\_") + "}"])
        mdrows.append(f"| {label} | {int(d['sec_count'])} | {int(d['sym_def'])}/{int(d['sym_undef'])} | "
                      f"{int(d['sym_weak'])} | {int(d['rel_total'])} (debug: {int(d['rel_debug'])}) | {top} |")
    tex_table(res / "table_symbols.tex",
              r"Language / mode & sections & def./undef. & weak & relocations & main type",
              body, "@{}lrrrrl@{}")
    md += ["## Sections, symbols, relocations\n",
           "| Language / mode | sections | def/undef | weak | relocations | main type |",
           "|---|---:|---:|---:|---:|---|", *mdrows, ""]

    # --- таблица времени и доли работы линкера
    body, mdrows = [], []
    for l, m in keys:
        d = agg[(l, m)]
        label = f"{tc.LANG_NAME[l]} {m}"
        body.append([label, n(d["compile_ms_median"]), n(d["max_rss_kb"] / 1024),
                     n(d["n_text_sections"]), n(d["n_groups"]), n(d["sym_undef"])])
        mdrows.append(f"| {label} | {d['compile_ms_median']:.0f} | {d['max_rss_kb'] / 1024:.0f} | "
                      f"{int(d['n_text_sections'])} | {int(d['n_groups'])} | {int(d['sym_undef'])} |")
    tex_table(res / "table_time.tex",
              r"Language / mode & time, ms & Max RSS, MB & \texttt{.text*} sections & COMDAT groups & undef.",
              body, "@{}lrrrrr@{}")
    md += ["## Compilation time and linker load\n",
           "Time: sum of medians across programs. Max RSS: maximum across programs. "
           "`.text*` sections and COMDAT groups show how many units `--gc-sections` can discard.\n",
           "| Language / mode | time, ms | Max RSS, MB | .text* sections | COMDAT groups | undef |",
           "|---|---:|---:|---:|---:|---:|", *mdrows, ""]

    # --- sizes.csv для pgfplots
    with open(res / "sizes.csv", "w") as f:
        f.write("lang,text,data,rodata,debug\n")
        for l in langs:
            d = agg.get((l, a.chart_mode))
            if d:
                f.write(f"{l},{int(d['sec_text'])},{int(d['sec_data'])},"
                        f"{int(d['sec_rodata'])},{int(d['sec_debug'])}\n")

    # --- типы релокаций (Markdown)
    md.append(f"## Типы релокаций, режим {a.chart_mode}\n")
    all_types = sorted({t for l in langs for t in rtypes[(l, a.chart_mode)]})
    if all_types:
        md += ["| Тип | " + " | ".join(tc.LANG_NAME[l] for l in langs) + " |",
               "|---|" + "---:|" * len(langs)]
        for t in all_types:
            md.append(f"| {t} | " + " | ".join(str(rtypes[(l, a.chart_mode)].get(t, 0)) for l in langs) + " |")
    (res / "summary.md").write_text("\n".join(md) + "\n")

    # --- графики
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib is not installed: charts skipped")
        print(f"written: {res}/sizes.csv, table_*.tex, summary.md")
        return

    fig, axes = plt.subplots(1, len(modes), figsize=(4.2 * len(modes), 3.6), squeeze=False)
    parts = [("sec_text", ".text"), ("sec_data", ".data"), ("sec_rodata", ".rodata"),
             ("sec_debug", ".debug_*"), ("sec_eh", ".eh_frame"), ("sec_other", "other")]
    for ax, m in zip(axes[0], modes):
        ls = [l for l in langs if (l, m) in agg]
        bottom = [0.0] * len(ls)
        for key, name in parts:
            vals = [agg[(l, m)][key] for l in ls]
            ax.bar([tc.LANG_NAME[l] for l in ls], vals, bottom=bottom, label=name)
            bottom = [b + v for b, v in zip(bottom, vals)]
        ax.set_title(f"mode {m}")
        ax.set_ylabel("bytes")
    axes[0][-1].legend(fontsize=7)
    fig.tight_layout()
    fig.savefig(res / "chart_sizes.png", dpi=150)

    m = a.chart_mode
    ls = [l for l in langs if (l, m) in agg]
    if ls:
        top = sorted({t for l in ls for t in rtypes[(l, m)]},
                     key=lambda t: -sum(rtypes[(l, m)][t] for l in ls))[:6]
        fig, ax = plt.subplots(figsize=(5, 3.6))
        bottom = [0] * len(ls)
        for t in top:
            vals = [rtypes[(l, m)].get(t, 0) for l in ls]
            ax.bar([tc.LANG_NAME[l] for l in ls], vals, bottom=bottom, label=t)
            bottom = [b + v for b, v in zip(bottom, vals)]
        ax.set_title(f"relocation types, mode {m}")
        ax.legend(fontsize=6)
        fig.tight_layout()
        fig.savefig(res / "chart_relocs.png", dpi=150)

        fig, (a1, a2) = plt.subplots(1, 2, figsize=(7, 3.4))
        a1.bar([tc.LANG_NAME[l] for l in ls], [agg[(l, m)]["compile_ms_median"] for l in ls])
        a1.set_title("compilation time, ms (sum)")
        a2.bar([tc.LANG_NAME[l] for l in ls], [agg[(l, m)]["max_rss_kb"] / 1024 for l in ls])
        a2.set_title("peak memory, MB")
        fig.tight_layout()
        fig.savefig(res / "chart_time.png", dpi=150)
    print(f"written: {res}/sizes.csv, table_*.tex, summary.md, chart_*.png")


if __name__ == "__main__":
    main()
